services:

  mongo:
    image: mongo:latest
    container_name: jobportal-mongo
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    networks:
      - jobportal-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: jobportal-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "5000:5000"

    depends_on:
      - mongo

    volumes:
      - uploads_data:/app/uploads

    networks:
      - jobportal-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: jobportal-frontend

    restart: unless-stopped

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - jobportal-network


volumes:
  mongo_data:
  uploads_data:


networks:
  jobportal-network:
    driver: bridge