apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: jobportal

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: ayaanb2324/jobportal-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

            - name: NODE_ENV
              value: "production"

            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/jobportal"

            - name: JWT_EXPIRE
              value: "1d"

            - name: FRONTEND_URL
              value: "http://localhost:8080"

            - name: CORS_ORIGIN
              value: "http://localhost:8080"

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET

            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GOOGLE_CLIENT_ID

            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GOOGLE_CLIENT_SECRET

            - name: GOOGLE_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GOOGLE_REDIRECT_URI

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10