apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: jobportal

type: Opaque

stringData:

  JWT_SECRET: "<YOUR_JWT_SECRET>"

  GOOGLE_CLIENT_ID: "<YOUR_GOOGLE_CLIENT_ID>"

  GOOGLE_CLIENT_SECRET: "<YOUR_GOOGLE_CLIENT_SECRET>"

  GOOGLE_REDIRECT_URI: "http://localhost:5000/api/oauth/google/callback"